trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Infrastructure'
  inputs:
    PathtoPublish: Infrastructure
    ArtifactName: Infrastructure
    publishLocation: 'pipeline'
