trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'Infrastructure'
    artifact: 'Infrastructure'
    publishLocation: 'pipeline'
